### PR TITLE
Add emmc support

### PR DESCRIPTION
**Pull request by detiber**
Adds the support needed for us-east-detiber

### CODE REVIEW

**Comment by detiber** [comment]
Still working on testing this build

**Comment by thebsdbox** [comment]
> Adds the support needed for us-east-detiber

Arguably the most import region! Thanks for the pr (once tested)

**Comment by detiber** [comment]
Looks like it is still missing something, will do some more digging...

**Comment by detiber** [comment]
Ok, updated and tested and successfully ran a workflow with these kernel changes.

It wasn't clear to me how the kernel is picked up through the build pipeline, though.

**Comment by gianarb** [comment]
Great! Yeah it is not clear because I do it manually right now. We didn't build a good story yet @thebsdbox

**Pull request merged**
